title: Segmentation Evaluation Tool
description: Segmentation Evaluation allows to segment an image in order to generate the GroundTruth. Moreover it evaluate the segmentation through precision and recall indicators.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
